name: ProjectExodus Github Actions
run-name: ${{ github.actor }} is verifying pull-request.
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  Check-Unity-Meta-Files:
    runs-on: ubuntu-latest
    steps:
      - name: Unity meta files check
        uses: DeNA/unity-meta-check@v4.0.0

